import React, { useState, useEffect } from 'react';
import './AdminReports.css';
import { auth, db } from '../firebase';
import { doc, getDoc, collection, query, where, getDocs } from 'firebase/firestore';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const AdminReports = () => {
    const [adminData, setAdminData] = useState(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        const fetchAdminData = async () => {
            if (auth.currentUser) {
                const docRef = doc(db, 'colleges', auth.currentUser.uid);
                const docSnap = await getDoc(docRef);
                if (docSnap.exists()) {
                    setAdminData(docSnap.data());
                }
            }
        };
        fetchAdminData();
    }, []);

    const handleDownloadReport = async () => {
        setLoading(true);
        const docPDF = new jsPDF();

        try {
            // --- 1. Fetch all necessary data ---
            const collegeId = auth.currentUser.uid;
            const studentsQuery = query(collection(db, "students"), where("collegeId", "==", collegeId));
            const facultyQuery = query(collection(db, "faculty"), where("collegeId", "==", collegeId));
            const activitiesQuery = query(collection(db, "certificateApprovalRequests"), where("status", "==", "approved"));

            const [studentSnapshot, facultySnapshot, activitySnapshot] = await Promise.all([
                getDocs(studentsQuery),
                getDocs(facultyQuery),
                getDocs(activitiesQuery)
            ]);
            
            const allStudents = studentSnapshot.docs.map(d => ({...d.data(), id: d.id }));
            const allFaculty = facultySnapshot.docs.map(d => d.data());
            const studentIds = allStudents.map(s => s.id);
            const allActivities = activitySnapshot.docs.map(d => d.data()).filter(a => studentIds.includes(a.studentId));

            // --- 2. Format data for PDF as requested ---
            // Section 1: Basic Information
            docPDF.setFontSize(18);
            docPDF.text("Institutional Report (NAAC)", 105, 22, { align: 'center' });
            docPDF.setFontSize(11);
            docPDF.text(`Institution: ${adminData?.institutionName || 'N/A'}`, 14, 32);
            docPDF.text(`Generated By: ${adminData?.adminName || 'N/A'} (${adminData?.adminEmail || ''})`, 14, 39);
            docPDF.text(`Date: ${new Date().toLocaleDateString()}`, 14, 46);
            
            const branchesText = `Branches: ${(adminData?.branches || []).join(', ')}`;
            const splitBranches = docPDF.splitTextToSize(branchesText, 180);
            docPDF.text(splitBranches, 14, 53);
            const tableStartY = 53 + (splitBranches.length * 5) + 10;

            // Section 2: Student Strength Table
            const strengthByBranchYear = allStudents.reduce((acc, student) => {
                const key = `${student.branch} - ${student.year}`;
                acc[key] = (acc[key] || 0) + 1;
                return acc;
            }, {});
            const strengthBody = Object.entries(strengthByBranchYear).map(([key, count]) => [key, count]);
            
            autoTable(docPDF, {
                startY: tableStartY,
                head: [['Student Strength (Dept & Year-wise)', 'Total Students']],
                body: strengthBody,
                theme: 'grid',
            });

            // --- NEW: Section for Faculty per Department ---
            const facultyByDept = allFaculty.reduce((acc, faculty) => {
                const dept = faculty.department || 'Unassigned';
                acc[dept] = (acc[dept] || 0) + 1;
                return acc;
            }, {});
            const facultyBody = Object.entries(facultyByDept).map(([dept, count]) => [dept, count]);

            autoTable(docPDF, {
                head: [['Faculty per Department', 'Total Faculty']],
                body: facultyBody,
                theme: 'grid',
            });

            // Section 3: Internship & Hackathon Table
            const internHackathon = allActivities.filter(a => a.activityType === 'Internship' || a.activityType === 'Hackathon');
            const internHackathonByDept = internHackathon.reduce((acc, activity) => {
                const student = allStudents.find(s => s.id === activity.studentId);
                const dept = student?.branch || 'Unassigned';
                acc[dept] = (acc[dept] || 0) + 1;
                return acc;
            }, {});
            const internHackathonBody = Object.entries(internHackathonByDept).map(([dept, count]) => [dept, count]);

            autoTable(docPDF, {
                head: [['Internships & Hackathons (Department-wise)', 'Total Submissions']],
                body: internHackathonBody,
                theme: 'grid',
            });
            
            // Section 4: Other Submissions Table
            const otherActivities = allActivities.filter(a => a.activityType !== 'Internship' && a.activityType !== 'Hackathon');
            const othersByDept = otherActivities.reduce((acc, activity) => {
                 const student = allStudents.find(s => s.id === activity.studentId);
                const dept = student?.branch || 'Unassigned';
                acc[dept] = (acc[dept] || 0) + 1;
                return acc;
            }, {});
            const othersBody = Object.entries(othersByDept).map(([dept, count]) => [dept, count]);
            
             autoTable(docPDF, {
                head: [['Other Submissions (Workshops, Sports, etc.)', 'Total Submissions']],
                body: othersBody,
                theme: 'grid',
            });

            // --- NEW: Section 5 - Additional Placeholder Data ---
            let finalY = (docPDF).lastAutoTable.finalY;
            docPDF.setFontSize(14);
            docPDF.setFont('helvetica', 'bold');
            docPDF.text("• Student Support & Progression", 14, finalY + 15);
            docPDF.setFontSize(11);
            docPDF.setFont('helvetica', 'normal');
            docPDF.text("Scholarships Provided: 2 | Placements: 67% | Alumni Meets Conducted: 0", 14, finalY + 22);


            docPDF.setFontSize(14);
            docPDF.setFont('helvetica', 'bold');
            docPDF.text("• Governance, Leadership & Management", 14, finalY + 32);
            docPDF.setFontSize(11);
            docPDF.setFont('helvetica', 'normal');
            docPDF.text("Institution Vision: To empower students through quality education and research.", 14, finalY + 39);


            docPDF.setFontSize(14);
            docPDF.setFont('helvetica', 'bold');
            docPDF.text("• Best Practices", 14, finalY + 49);
            docPDF.setFontSize(11);
            docPDF.setFont('helvetica', 'normal');
            docPDF.text("• Green Campus Initiative | • Digital Learning Resources | • Community Engagement Programs", 14, finalY + 56);



            
            // --- 3. Save the PDF ---
            docPDF.save(`${adminData?.institutionName || 'NAAC'}_Report.pdf`);

        } catch (error) {
            console.error("Failed to generate report:", error);
            alert("An error occurred while generating the report.");
        } finally {
            setLoading(false);
        }
    };
    
    return (
        <div>
            {/* <div className="page-header">
                <h2>Reports</h2>
                <p>Generate comprehensive institutional reports</p>
            </div> */}
            <div className="reports-banner">
                <h3>Reports</h3>
                <p>Generate comprehensive institutional reports</p>
            </div>

            <div className="reports-grid">
                <div className="report-card">
                    <div className="report-header">
                        <h4>NAAC Report</h4>
                        <p>Last generated: {new Date().toLocaleDateString()}</p>
                    </div>
                    <span className="report-status">Ready</span>
                    <p className="report-description">National Assessment and Accreditation Council report focusing on student progression and support.</p>
                    <div className="report-actions">
                        <button onClick={handleDownloadReport} className="btn-download" disabled={loading}>
                            {loading ? 'Generating...' : 'Download'}
                        </button>
                    </div>
                </div>
                <div className="report-card">
                    <div className="report-header"><h4>AICTE Report</h4></div>
                    <span className="report-status-pending">Pending</span>
                    <p className="report-description">All India Council for Technical Education report.</p>
                    <div className="report-actions"><button onClick={() => alert("AICTE Report is not available yet.")} className="btn-download">Download</button></div>
                </div>
                <div className="report-card">
                    <div className="report-header"><h4>NIRF Report</h4></div>
                    <span className="report-status-pending">Pending</span>
                    <p className="report-description">National Institutional Ranking Framework data.</p>
                    <div className="report-actions"><button onClick={() => alert("NIRF Report is not available yet.")} className="btn-download">Download</button></div>
                </div>
                <div className="report-card">
                    <div className="report-header"><h4>Internal Audit</h4></div>
                    <span className="report-status-pending">Pending</span>
                    <p className="report-description">Internal institutional audit report.</p>
                    <div className="report-actions"><button onClick={() => alert("Internal Audit Report is not available yet.")} className="btn-download">Download</button></div>
                </div>
            </div>
        </div>
    );
};

export default AdminReports;

























// import React, { useState, useEffect } from 'react';
// import './AdminReports.css';
// import { auth, db } from '../firebase';
// import { doc, getDoc, collection, query, where, getDocs } from 'firebase/firestore';
// import jsPDF from 'jspdf';
// import autoTable from 'jspdf-autotable';

// const AdminReports = () => {
//     const [adminData, setAdminData] = useState(null);
//     const [loading, setLoading] = useState(false);

//     useEffect(() => {
//         const fetchAdminData = async () => {
//             if (auth.currentUser) {
//                 const docRef = doc(db, 'colleges', auth.currentUser.uid);
//                 const docSnap = await getDoc(docRef);
//                 if (docSnap.exists()) {
//                     setAdminData(docSnap.data());
//                 }
//             }
//         };
//         fetchAdminData();
//     }, []);

//     const handleDownloadReport = async () => {
//         setLoading(true);
//         const docPDF = new jsPDF();

//         try {
//             // --- 1. Fetch all necessary data ---
//             const collegeId = auth.currentUser.uid;
//             const studentsQuery = query(collection(db, "students"), where("collegeId", "==", collegeId));
//             const facultyQuery = query(collection(db, "faculty"), where("collegeId", "==", collegeId));
//             const activitiesQuery = query(collection(db, "certificateApprovalRequests"), where("status", "==", "approved"));

//             // --- CORRECTED DATA FETCHING ---
//             const [studentSnapshot, facultySnapshot ,activitySnapshot] = await Promise.all([
//                 getDocs(studentsQuery),
//                 getDocs(facultyQuery),
//                 getDocs(activitiesQuery)
//             ]);
            
//             const allStudents = studentSnapshot.docs.map(d => ({...d.data(), id: d.id }));
//             const allFaculty = facultySnapshot.docs.map(d => d.data());
//             const studentIds = allStudents.map(s => s.id);
//             const allActivities = activitySnapshot.docs.map(d => d.data()).filter(a => studentIds.includes(a.studentId));

//             // --- 2. Format data for PDF as requested ---
//             // Section 1: Basic Information
//             docPDF.setFontSize(18);
//             docPDF.text("Institutional Report (NAAC)", 105, 22, { align: 'center' });
//             docPDF.setFontSize(11);
//             docPDF.text(`Institution: ${adminData?.institutionName || 'N/A'}`, 14, 32);
//             docPDF.text(`Generated By: ${adminData?.adminName || 'N/A'} (${adminData?.adminEmail || ''})`, 14, 39);
//             docPDF.text(`Date: ${new Date().toLocaleDateString()}`, 14, 46);
            
//              // --- CORRECTED: Handle long list of branches ---
//             const branchesText = `Branches: ${(adminData?.branches || []).join(', ')}`;
//             const splitBranches = docPDF.splitTextToSize(branchesText, 180); // 180mm is the max width
//             docPDF.text(splitBranches, 14, 53);
            
//             // Calculate where the first table should start, based on how many lines the branches took up
//             const tableStartY = 53 + (splitBranches.length * 5) + 10;

//             // Section 2: Student Strength Table
//             const strengthByBranchYear = allStudents.reduce((acc, student) => {
//                 const key = `${student.branch} - ${student.year}`;
//                 acc[key] = (acc[key] || 0) + 1;
//                 return acc;
//             }, {});
//             const strengthBody = Object.entries(strengthByBranchYear).map(([key, count]) => [key, count]);
            
//             autoTable(docPDF, {
//                 startY: tableStartY,
//                 head: [['Student Strength (Branch & Year-wise)', 'Total Students']],
//                 body: strengthBody,
//                 theme: 'grid',
//             });

//             // --- NEW: Section for Faculty per Department ---
//             const facultyByDept = allFaculty.reduce((acc, faculty) => {
//                 const dept = faculty.department || 'Unassigned';
//                 acc[dept] = (acc[dept] || 0) + 1;
//                 return acc;
//             }, {});
//             const facultyBody = Object.entries(facultyByDept).map(([dept, count]) => [dept, count]);

//             autoTable(docPDF, {
//                 head: [['Faculty per Department', 'Total Faculty']],
//                 body: facultyBody,
//                 theme: 'grid',
//             });

//             // Section 3: Internship & Hackathon Table
//             const internHackathon = allActivities.filter(a => a.activityType === 'Internship' || a.activityType === 'Hackathon');
//             const internHackathonByDept = internHackathon.reduce((acc, activity) => {
//                 const student = allStudents.find(s => s.id === activity.studentId);
//                 const dept = student?.branch || 'Unassigned';
//                 acc[dept] = (acc[dept] || 0) + 1;
//                 return acc;
//             }, {});
//             const internHackathonBody = Object.entries(internHackathonByDept).map(([dept, count]) => [dept, count]);

//             autoTable(docPDF, {
//                 head: [['Internships & Hackathons (Department-wise)', 'Total Submissions']],
//                 body: internHackathonBody,
//                 theme: 'grid',
//             });
            
//             // Section 4: Other Submissions Table
//             const otherActivities = allActivities.filter(a => a.activityType !== 'Internship' && a.activityType !== 'Hackathon');
//             const othersByDept = otherActivities.reduce((acc, activity) => {
//                  const student = allStudents.find(s => s.id === activity.studentId);
//                 const dept = student?.branch || 'Unassigned';
//                 acc[dept] = (acc[dept] || 0) + 1;
//                 return acc;
//             }, {});
//             const othersBody = Object.entries(othersByDept).map(([dept, count]) => [dept, count]);
            
//              autoTable(docPDF, {
//                 head: [['Other Submissions (Workshops, Sports, etc.)', 'Total Submissions']],
//                 body: othersBody,
//                 theme: 'grid',
//             });

//             <h2> 4. Student Support & Progression</h2>
            

//             // --- 3. Save the PDF ---
//             docPDF.save(`${adminData?.institutionName || 'NAAC'}_Report.pdf`);

//         } catch (error) {
//             console.error("Failed to generate report:", error);
//             alert("An error occurred while generating the report.");
//         } finally {
//             setLoading(false);
//         }
//     };
    
//     return (
//         <div>
//             <div className="page-header">
//                 <h2>Reports</h2>
//                 <p>Generate comprehensive institutional reports</p>
//             </div>
//             <div className="reports-banner">
//                 <h3>Reports</h3>
//                 <p>Generate comprehensive institutional reports</p>
//             </div>

//             <div className="reports-grid">
//                 <div className="report-card">
//                     <div className="report-header">
//                         <h4>NAAC Report</h4>
//                         <p>Last generated: {new Date().toLocaleDateString()}</p>
//                     </div>
//                     <span className="report-status">Ready</span>
//                     <p className="report-description">National Assessment and Accreditation Council report focusing on student progression and support.</p>
//                     <div className="report-actions">
//                         <button onClick={handleDownloadReport} className="btn-download" disabled={loading}>
//                             {loading ? 'Generating...' : 'Download'}
//                         </button>
//                     </div>
//                 </div>
//                 <div className="report-card">
//                     <div className="report-header"><h4>AICTE Report</h4></div>
//                     <p className="report-description">All India Council for Technical Education report.</p>
//                     <div className="report-actions"><button disabled className="btn-download">Download</button></div>
//                 </div>
//                 <div className="report-card">
//                     <div className="report-header"><h4>NIRF Report</h4></div>
//                     <p className="report-description">National Institutional Ranking Framework data.</p>
//                     <div className="report-actions"><button disabled className="btn-download">Download</button></div>
//                 </div>
//                 <div className="report-card">
//                     <div className="report-header"><h4>Internal Audit</h4></div>
//                     <p className="report-description">Internal institutional audit report.</p>
//                     <div className="report-actions"><button disabled className="btn-download">Download</button></div>
//                 </div>
//             </div>
//         </div>
//     );
// };

// export default AdminReports;
